### ISSUE TITLE
dockerHubDescription fails (Response Code: 415)

### ISSUE THREAD

**Issue by ncvescera** [qdm12/latexdevcontainer#41]
The dockerHubDescription action fails when 

```
Run peter-evans/dockerhub-description@v2.1.0
```

Could be the old version of `peter-evans/dockerhub-description@v2.1.0 ` (the new one is `peter-evans/dockerhub-description@v3`) ?

We should also update Actions `.yml` files to the new Node 16 version.

**Comment by qdm12** [comment]
Definitely! Just got lazy updating around. I'll check the dependabot PRs now.

**Comment by qdm12** [comment]
Oops there is no dependabot...

Maybe time to add it? I'm on my phone right now, but adding a file as .github/dependabot.yml with

```yml
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: "daily"
```

Should do 😉
