### ISSUE TITLE
labels.yml file ?

### ISSUE THREAD

**Issue by ncvescera** [qdm12/latexdevcontainer#43]
Is the file `.github/labels.yml` an attempt to add the [ghaction-github-labeler](https://github.com/crazy-max/ghaction-github-labeler) auto labels generator Action ?

If so, I will add the following file `.github/githublabeler.yml`:

```yml
name: "Github Labeler"

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/githublabeler.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
          exclude: |
            help*
            *issue
```
