### ISSUE TITLE
container build failed !

### ISSUE THREAD

**Issue by ravikumargrk** [qdm12/latexdevcontainer#51]
I have created a codespace and built container using your .devcontainer config untouched.
build has failed.

**Comment by ncvescera** [comment]
> I have created a codespace and built container using your .devcontainer config untouched. build has failed.

Hallo 🌈 
thank you for your feedback. I'll check ASAP.

Could you attach the error message ?
Are you on Linux, Windows, MacOS ?

**Comment by ncvescera** [comment]
@ravikumargrk I found the problem.

When you are creating and using a Github Codespace, there are no files like `~/.gitconfig`, `~/.ssh`, etc.

Try with commenting all the volumes inside the `docker-compose.yml` file (except for `../` and `/var/run/docker.sock`).
The following code should works:

```yml
version: "3.2"

services:
  vscode:
    build: .
    image: latexdevcontainer
    volumes:
      - ../:/workspace
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory
      # - ~/.ssh:/root/.ssh
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      # - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      # - ~/.gitconfig:/root/.gitconfig
    environment:
      - TZ=
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
```
